local options = {
	title = true,
	autoindent = true,
	hlsearch = true,
	showtabline = 2,
	tabstop = 2,
	shiftwidth = 2,
	number= true,
	relativenumber = true,
	pumblend = 25,
	termguicolors = true,
	backup = false,
	showcmd = true,
	cmdheight = 1,
	laststatus = 2,
	expandtab = true,
	scrolloff = 10,
	shell = 'fish',
	inccommand = 'split',
	ignorecase = true,
	smarttab = true,
	breakindent = true,
	ai = true,
	si = true,
	wrap = false,
	backspace = 'start,eol,indent',
  clipboard="unnamed",
  shell = vim.fn.executable "pwsh" == 1 and "pwsh" or "powershell",
  shellcmdflag = "-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;",
  shellredir = "-RedirectStandardOutput %s -NoNewWindow -Wait",
  shellpipe = "2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode",
  shellquote = "",
  shellxquote = "",
}

for k,v in pairs(options) do
	vim.opt[k] = v
end
